[build]
base = "/"
command = "pnpm run build"
publish = "/apps/web/dist"

[build.environment]
NODE_VERSION = "24"
NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
